#define	DEFAULT_TABLE		"users"

#define USERS_USERNAME		"username"
#define USERS_PASSWD		"passwd"
#define USERS_UID		"uid"
#define USERS_GID		"gid"
#define USERS_COMMENT		"comment"
#define USERS_HOMEDIR		"homedir"
#define USERS_LASTCHANGE	"lastchange"
#define USERS_MINCHANGE		"minchange"
#define USERS_MAXCHANGE		"maxchange"
#define USERS_WARN		"warn"
#define USERS_INACT		"inact"
#define USERS_EXPIRE		"expire"
#define USERS_LOCKDATE		"updatedby"
#define USERS_LOCKEDBY		"updatedate"
#define USERS_LOCKCOMMENT	"updateaction"
