#!/bin/bash
####################################################################
#
#  auto_label - generate an autofs entry based on label or device.
#
unset DEVICE ID_FS_TYPE FS_TYPE OPTS MOUNTED RO PAIR INDEX_RO INDEX_RW

if [ -e "/dev/disk/by-label/$1" ] ; then
	DEVICE="$(realpath "/dev/disk/by-label/$1")"
else
	if [ -e "/dev/$1" ] ; then
		DEVICE="/dev/$1"
	else
		exit
	fi
fi

MOUNTED=($(grep "^${DEVICE}" /proc/mounts))
if [ "${PWD}" = "/cygdrive" ] ; then
	if [ -n "${MOUNTED[0]}" ] ; then
		mount "${MOUNTED[0]}" -o rw,noatime,remount
	fi
else
	if [ "${PWD}" = "/multimedia" ] ; then
		if [ -z "${MOUNTED[0]}" ] ; then
			RO=",ro"
		fi
	fi
fi

export $(blkid -o udev "$DEVICE") >/dev/null
[ -z "$ID_FS_TYPE" ] && exit

case "$ID_FS_TYPE" in
	ntfs)
		FS_TYPE="ufsd"
		OPTS="${RO},noatime,fmask=0133,uid=$UID,gid=$GID"
		;;
	vfat)
		FS_TYPE="vfat"
		OPTS="${RO},noatime,fmask=0133,uid=$UID,gid=$GID"
		;;
	ext2 | ext3 | ext4)
		FS_TYPE="ext4"
		OPTS="${RO},noatime"
		;;
	   *)
		FS_TYPE="$ID_FS_TYPE"
		OPTS="${RO},"
		;;
esac

echo "-fstype=${FS_TYPE}${OPTS} :${DEVICE}"
